services:
  - type: web
    name: pokemon-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/pokemon-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html